export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: 'Afeganistão', code: '+93', flag: '🇦🇫' },
  { name: 'África do Sul', code: '+27', flag: '🇿🇦' },
  { name: 'Albânia', code: '+355', flag: '🇦🇱' },
  { name: 'Alemanha', code: '+49', flag: '🇩🇪' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩' },
  { name: 'Angola', code: '+244', flag: '🇦🇴' },
  { name: 'Anguila', code: '+1', flag: '🇦🇮' },
  { name: 'Antígua e Barbuda', code: '+1', flag: '🇦🇬' },
  { name: 'Arábia Saudita', code: '+966', flag: '🇸🇦' },
  { name: 'Argélia', code: '+213', flag: '🇩🇿' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷' },
  { name: 'Armênia', code: '+374', flag: '🇦🇲' },
  { name: 'Aruba', code: '+297', flag: '🇦🇼' },
  { name: 'Austrália', code: '+61', flag: '🇦🇺' },
  { name: 'Áustria', code: '+43', flag: '🇦🇹' },
  { name: 'Bahamas', code: '+1', flag: '🇧🇸' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩' },
  { name: 'Barbados', code: '+1', flag: '🇧🇧' },
  { name: 'Bélgica', code: '+32', flag: '🇧🇪' },
  { name: 'Belize', code: '+501', flag: '🇧🇿' },
  { name: 'Bolívia', code: '+591', flag: '🇧🇴' },
  { name: 'Brasil', code: '+55', flag: '🇧🇷' },
  { name: 'Camarões', code: '+237', flag: '🇨🇲' },
  { name: 'Canadá', code: '+1', flag: '🇨🇦' },
  { name: 'Chile', code: '+56', flag: '🇨🇱' },
  { name: 'China', code: '+86', flag: '🇨🇳' },
  { name: 'Colômbia', code: '+57', flag: '🇨🇴' },
  { name: 'Coreia do Sul', code: '+82', flag: '🇰🇷' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺' },
  { name: 'Dinamarca', code: '+45', flag: '🇩🇰' },
  { name: 'Egito', code: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻' },
  { name: 'Emirados Árabes', code: '+971', flag: '🇦🇪' },
  { name: 'Equador', code: '+593', flag: '🇪🇨' },
  { name: 'Espanha', code: '+34', flag: '🇪🇸' },
  { name: 'Estados Unidos', code: '+1', flag: '🇺🇸' },
  { name: 'Filipinas', code: '+63', flag: '🇵🇭' },
  { name: 'França', code: '+33', flag: '🇫🇷' },
  { name: 'Grécia', code: '+30', flag: '🇬🇷' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳' },
  { name: 'Índia', code: '+91', flag: '🇮🇳' },
  { name: 'Indonésia', code: '+62', flag: '🇮🇩' },
  { name: 'Irlanda', code: '+353', flag: '🇮🇪' },
  { name: 'Israel', code: '+972', flag: '🇮🇱' },
  { name: 'Itália', code: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', code: '+1', flag: '🇯🇲' },
  { name: 'Japão', code: '+81', flag: '🇯🇵' },
  { name: 'Marrocos', code: '+212', flag: '🇲🇦' },
  { name: 'México', code: '+52', flag: '🇲🇽' },
  { name: 'Nigéria', code: '+234', flag: '🇳🇬' },
  { name: 'Nova Zelândia', code: '+64', flag: '🇳🇿' },
  { name: 'Panamá', code: '+507', flag: '🇵🇦' },
  { name: 'Paraguai', code: '+595', flag: '🇵🇾' },
  { name: 'Peru', code: '+51', flag: '🇵🇪' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹' },
  { name: 'Reino Unido', code: '+44', flag: '🇬🇧' },
  { name: 'Rússia', code: '+7', flag: '🇷🇺' },
  { name: 'Suécia', code: '+46', flag: '🇸🇪' },
  { name: 'Suíça', code: '+41', flag: '🇨🇭' },
  { name: 'Turquia', code: '+90', flag: '🇹🇷' },
  { name: 'Ucrânia', code: '+380', flag: '🇺🇦' },
  { name: 'Uruguai', code: '+598', flag: '🇺🇾' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪' },
];
